//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telefonkonyv_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CimSet
    {
        public int Id { get; set; }
        public int SzemelyId { get; set; }
    
        public virtual SzemelySet SzemelySet { get; set; }
    }
}
