//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telefonkonyv_WPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TelefonkonyvEntities : DbContext
    {
        public TelefonkonyvEntities()
            : base("name=TelefonkonyvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kontaktok> Kontaktoks { get; set; }
        public virtual DbSet<Telefonszamok> Telefonszamoks { get; set; }
        public virtual DbSet<CimSet> CimSets { get; set; }
        public virtual DbSet<SzemelySet> SzemelySets { get; set; }
    }
}
