//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telefonkonyv_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefonszamok
    {
        public int ID { get; set; }
        public string Telefonszam { get; set; }
        public string Tipus { get; set; }
        public int KontaktID { get; set; }
    
        public virtual Kontaktok Kontaktok { get; set; }
    }
}
